# 1-3. NUMPY 

### 넘파이 ndarray 개요

넘파이의 기반 데이터 타입은 ndarray이다. ndarray는 다차원 배열을 쉬게 생성하고 다양한 연산을 수행할 수 있다. 넘파이 array함수는 파이썬의 리스트와 같은 다양한 인자를 입력바다 ndarray로 변환하는 기능을 수행한다. 

In [32]:
import pandas as pd
import numpy as np # 약어로 쓰는 것이 관례
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [42]:
array1=np.array([1,2,3]) #[]를 1개 써서 1차원
print('array1 type:',type(array1))
print('array1 형태:',array1.shape)

array2=np.array([[1,2,3],
                [2,3,4]]) 
print('array2 type:',type(array2))
print('array2 형태:',array2.shape)

array3=np.array([[1,2,3]]) # []를 2개 써서 2차원 => low와 column 존재
print('array3 type:',type(array3))
print('array3 형태:',array3.shape)


print(array1.ndim)
print('array1:{:0}차원,\narray2:{:1}차원\narray3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 형태: (1, 3)
1
array1:1차원,
array2:2차원
array3: 2차원


#### cf) 위의 마지막 코드에서 {},format()을 쓸 때 {} 안에 콜론(:)의 의미
콜론 앞에 있는 숫자는 format에서 넣을 인자의 순서를 나타내는 것이다. 공란으로 두면 알아서 순서대로 배열됩니다.
콜론 뒤에있는 0,1,2는 자릿수를 나타내는 것입니다. array3의 경우 {:2}이므로 숫자가 2자리 수를 쓸 때처럼 배열되어 띄어쓰기가 된 상태가 됩니다
출처: https://blockdmask.tistory.com/424

### ndarray의 데이터 타입

In [33]:
# list를 ndarray화 - np.array()
list1=[1,2,3]
print(type(list1))
array1=np.array(list1) 
print(type(array1)) 
print(array1,array1.dtype)

# array내의 데이터값은 모두 int32, list는 서로 다른 데이터 타입을 원소로 가질 수 있다
# list를 ndarray화 시 데이터 크기가 더 큰 데이터 타입으로 형변환 일괄적용
list2=[1,2,'test'] # 문자형 변수
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0] # float이 있는 array
array3=np.array(list3)
print(array3,array3.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64



In [35]:
# ndarray.astype()
array_int = np.array([1,2,3])
array_float=array_int.astype('float64')#float으로 array 전체 형변환
print(array_float,array_float.dtype)

array_int1 =array_float.astype('int32')#int으로 array 전체 형변환
print(array_int1,array_int1.dtype)

array_float1 =np.array([1.1,2.1,3.1]) 
array_int2 =array_float1.astype('int32') #float이 int가 되며 실제값과 차이가 난다
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - np.arange(),np.zeros(), np.ones()

In [41]:
# np.arange(),np.zeros(), np.ones()함수와 dtype인자
sequence_array = np.arange(10) # 0~(n-1)까지의 int형 array를 만든다. (start, stop+1,step)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array=np.zeros((3,2),dtype='int32') # np.zeros()로 0으로만 이루어진 array 생성, dtype으로 데이터 타입 정하기
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2)) # np.ones()로 1으로만 이루어진 array 생성, dtype 디폴트값은 float64
print(one_array)
print(one_array.dtype,one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 ndarray.reshape()

In [47]:
# ndarray.reshape() 함수 - 이 때 데이터 수와 dimension이 딱 나누어 떨어져야 한다
array1=np.arange(10)
print('arrray1:\n',array1)

array2=array1.reshape(2,5) # reshape함수를 통해 dimension변환
print('arrray2:\n',array2)

array3=array1.reshape(5,2) # reshape함수를 통해 dimension변환
print('arrray3:\n',array3)

arrray1:
 [0 1 2 3 4 5 6 7 8 9]
arrray2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arrray3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [50]:
# reshape()에 인자로 -1적용 시 눈치껏 알맞은 배열로 자동으로 만든다.(나누어떨어질때만 OK)
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array2=array1.reshape(5,-1)
print('array2 shape:',array2.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2 shape: (5, 2)


In [60]:
# ndarray.reshape(-1,1) => 3차원과 1차원의 array를 2차원의 array로 변환 가능하다

array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1) # 1열로 쭉 배열
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 array를 2차원 ndarray로 변환
array6=array1.reshape(-1,1) # 1열로 쭉 배열
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

In [66]:
# 인덱싱으로 단일 값 추출 - 1차원에서
array1=np.arange(start=1,stop=10) # 1부터 9까지의 1차원 ndarray생성
print('array1:',array1)
# index는 0부터 시작하므로 array1[2]는 3번째 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))
# index는 음수인 경우 -1부터 시작(맨 마지막값)
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

# ndarray 내의 데이터값 수정 가능
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]


In [35]:
# 인덱싱으로 단일 값 추출 - 2차원에서
array1d=np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print('(row=0, col=0) index가 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index가 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index가 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index가 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index가 가리키는 값: 1
(row=0, col=1) index가 가리키는 값: 2
(row=1, col=0) index가 가리키는 값: 4
(row=2, col=2) index가 가리키는 값: 9


In [75]:
# :를 이용한 슬라이싱 - 1차원에서
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

array1=np.arange(start=1,stop=10)
array4=array1[:3] # 시작 및 종료 인덱스 생략가능
print(array4)

array5=array1[3:] # 시작 및 종료 인덱스 생략가능
print(array5)

array6=array1[:] # 전체 의미. 복사하고 싶을 때 사용
print(array6)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [36]:
# :를 이용한 슬라이싱 - 2차원에서
array1=np.arange(start=1,stop=10)
array2d= array1.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])

print(array2d[0]) # 첫 행을 출력
print(array2d[1]) # 두번째 행을 출력
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape, )

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [86]:
# 팬시 인덱싱(Fancy Indexing) - 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식
# 2차원 인덱싱 + 슬라이싱
# cf) ndarray.tolist()로 리스트 형태로 만들 수 있다.
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [7]:
# 불린 인덱싱
array1d=np.arange(1,10)
array3 = array1d[array1d>5] # []안에 array1d>5 boolean indexing을 적용
print('array1d>5 불린 인덱싱 결과 값:',array3)

print(array1d>5)
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array2=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]
[False False False False False  True  True  True  True]
불린 인덱스로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


### 행렬의 정렬 - np.sort(), ndarray.sort(),np.argsort()

In [17]:
# 1차원에서 정렬 - np.sort(ndarray)와 ndarray.sort()를 통해 array 정렬
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)
# np.sort()로 정렬 => 원본 array는 변하지 않는다. 새로 지정한 array는 sort된 형태
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬 => 원본 array가 정렬된다
sort_array2=org_array.sort() # 이것은 값을 반환하는 것이 아니라 array를 변화시키키만 하는 함수이다. 따라서, None이 출력된다
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

# 내림차순 정렬
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


In [19]:
# 2차원에서의 정렬 - axis 축 값 설정
array2d=np.array([[8,12],
                 [7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('Row 방향으로 정렬\n:',sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print('Column 방향으로 정렬\n:',sort_array2d_axis1)

Row 방향으로 정렬
: [[ 7  1]
 [ 8 12]]
Column 방향으로 정렬
: [[ 8 12]
 [ 1  7]]


In [22]:
# 정렬된 행렬의 인덱스 반환하기 - np.argsort()
org_array = np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)
# 내림차순으로 정렬된 행렬의 인덱스 반환하기 - np.argsort()[::-1]
org_array = np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


argsort()는 넘파이의 데이터 추출에서 많이 사용된다. 2개의 ndarray(index 와 value)가 있고 딕셔너리처럼 이용해야 할 때, np.argsort()를 사용한다.
- EX)name_array(=학생명)와 score_array(=성적)가 있다. 여기서 성적 낮은순으로 학생명을 나열할 때 다음과 같다

In [28]:
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순dmfh name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순dmfh name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [31]:
# 행렬의 내적 -np.dot()
A= np.array([[1,2,3],
            [4,5,6]])
B= np.array([[7,8],
            [9,10],
            [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

# 전치 행렬 - np.transpose()
A= np.array([[1,2],
            [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]
