# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [31]:
x=np.array([1,4,5,6,6])
x.size * x.itemsize

20

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
x=np.array([1,2,3,4,5])
x[::-1]

array([5, 4, 3, 2, 1])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
x=np.arange(0,9)
mat=x.reshape(-1,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
x=np.array([1,2,0,0,4,0])
index=np.arange(6)[x!=0]
print(index)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [48]:
a=np.arange(9).reshape(3,3)
b=np.invert(a)
# sol1 
print(np.diag(np.ones(3)))

# sol2
print(np.identity(3))

# sol3
?np.eye

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [20]:
np.random.random(27).reshape(3,3,3)

array([[[0.14620328, 0.11574121, 0.6331805 ],
        [0.63142463, 0.46111467, 0.93702765],
        [0.15745395, 0.79560514, 0.34382024]],

       [[0.56060218, 0.04157626, 0.82431991],
        [0.18308663, 0.56420711, 0.70260439],
        [0.69324747, 0.7555675 , 0.90312093]],

       [[0.45395579, 0.82837858, 0.95969351],
        [0.45624016, 0.36864442, 0.36642012],
        [0.51291211, 0.48274149, 0.6036471 ]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [35]:
x=np.random.random(100).reshape(10,10)
print(x)
print("최대:",np.max(x), "최소",np.min(x))

[[9.28138622e-01 7.52904750e-01 6.96155415e-02 4.08708555e-02
  7.97720159e-01 2.78661918e-01 9.40991224e-01 4.10743040e-01
  4.49674331e-01 7.74516465e-01]
 [3.99088062e-01 1.45574201e-01 1.93301700e-01 2.43878470e-01
  6.72852429e-01 4.44704837e-01 9.16403234e-02 1.14786948e-01
  7.22013397e-01 6.48993088e-01]
 [3.16191946e-01 4.75495851e-01 2.36075905e-01 7.32007336e-01
  5.11280080e-01 3.08605520e-01 5.01914637e-01 4.28217375e-01
  4.68050013e-01 8.41214122e-01]
 [6.49577119e-01 3.93384231e-01 9.36070867e-01 8.54608218e-01
  1.20167301e-01 2.82414744e-01 2.95948419e-01 7.73906037e-01
  3.13449929e-01 7.41359134e-01]
 [8.81163530e-01 9.04186784e-01 7.24539500e-01 8.14587615e-01
  6.25578705e-01 3.62491624e-01 3.79666033e-01 9.17238393e-01
  1.25097666e-01 8.62710574e-01]
 [1.41416630e-01 8.60090485e-04 1.77321735e-01 1.68215376e-02
  7.47127237e-01 4.30291399e-01 7.92988282e-01 4.85461276e-02
  7.64661089e-01 5.27157185e-01]
 [4.82554498e-01 5.24299478e-01 8.66661875e-01 8.83975649e

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [49]:
x=np.random.random(30)
print(x)
print("평균:",np.mean(x))

[0.75743569 0.7050792  0.17541181 0.83081482 0.25325885 0.27428696
 0.07889888 0.32525933 0.38683589 0.17529378 0.63723993 0.88382845
 0.35605233 0.41902389 0.49557209 0.41103691 0.86024652 0.65387967
 0.89428798 0.30821635 0.82286357 0.68507077 0.1623755  0.00461679
 0.2968339  0.90007023 0.96906401 0.52495662 0.75085912 0.17418526]
평균: 0.5057618362918986


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [52]:
n=5
x=np.ones(n*n).reshape(n,n)
x[1:n-1,1:n-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [53]:
0 * np.nan   # nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True =>{nan}인 집합이므로 nan이 안에 들어있다고 볼 수 있다
0.3 == 3 * 0.1 # False

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [75]:
x=np.zeros(25).reshape(5,5)
for i in list(range(5)):
    for j in list(range(5)):
        if j-i==-1:
            x[i,j]=j+1
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [81]:
# sol1
x=np.zeros(64).reshape(8,8)
for i in list(range(8)):
    for j in list(range(8)):
        if (i+j)%2==1:
            x[i,j]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [83]:
# sol2
x=np.zeros(64).reshape(8,8)
x[::2,1::2]=1
x[1::2,::2]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [88]:
x=np.random.random(25).reshape(5,5)
z=(x-np.mean(x))/np.std(x)
z

array([[-1.04875369,  1.52254412, -0.32519207, -0.98732709,  1.25641054],
       [-0.20493822, -1.10286599,  1.30609414,  0.21922786,  1.95321071],
       [-0.84878158,  0.33501997, -0.34604069,  0.92352787, -1.16539873],
       [-0.63913865,  1.68135783,  0.79020535, -1.08166195, -1.09219286],
       [-1.06284491,  0.49284446, -0.94369423, -0.25076082,  0.61914864]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3